/**
 * All analytics event names for @relayprotocol/relay-kit-ui-v2.
 *
 * Usage pattern: pass an `onAnalyticEvent` callback to the provider or widget:
 *   <RelayKitProvider onAnalyticEvent={(name, data) => analytics.track(name, data)}>
 *
 * Every event from relay-kit-ui v1 is preserved here (excluding onramp-specific
 * events which are not part of the swap widget scope).
 */
export const EventNames = {
  // Swap widget core events
  SWAP_CTA_CLICKED: 'SWAP_CTA_CLICKED',
  QUOTE_ERROR: 'QUOTE_ERROR',
  SWAP_ERROR: 'SWAP_ERROR',
  SWAP_INPUT_FOCUSED: 'SWAP_INPUT_FOCUSED',
  SWAP_OUTPUT_FOCUSED: 'SWAP_OUTPUT_FOCUSED',
  SWAP_ADDRESS_MODAL_CLICKED: 'SWAP_ADDRESS_MODAL_CLICKED',
  SWAP_SWITCH_NETWORK: 'SWAP_SWITCH_NETWORK',
  QUOTE_REQUESTED: 'QUOTE_REQUESTED',
  QUOTE_RECEIVED: 'QUOTE_RECEIVED',
  SWAP_SLIPPAGE_TOLERANCE_SET: 'SWAP_SLIPPAGE_TOLERANCE_SET',

  // Deposit address modal events
  DEPOSIT_ADDRESS_MODAL_OPEN: 'DEPOSIT_ADDRESS_MODAL_OPEN',
  DEPOSIT_ADDRESS_MODAL_CLOSED: 'DEPOSIT_ADDRESS_MODAL_CLOSED',
  DEPOSIT_ADDRESS_SWAP_ERROR: 'DEPOSIT_ADDRESS_SWAP_ERROR',

  // Transaction modal events
  SWAP_MODAL_OPEN: 'SWAP_MODAL_OPEN',
  SWAP_MODAL_CLOSED: 'SWAP_MODAL_CLOSED',

  // Token selector events
  SWAP_START_TOKEN_SELECT: 'SWAP_START_TOKEN_SELECT',
  SWAP_TOKEN_SELECT: 'SWAP_TOKEN_SELECT',
  SWAP_EXIT_TOKEN_SELECT: 'SWAP_EXIT_TOKEN_SELECT',

  // Transaction lifecycle events
  DEPOSIT_SUBMITTED: 'DEPOSIT_SUBMITTED',
  APPROVAL_SUBMITTED: 'APPROVAL_SUBMITTED',
  APPROVAL_SUCCESS: 'APPROVAL_SUCCESS',
  APPROVAL_ERROR: 'APPROVAL_ERROR',
  DEPOSIT_SUCCESS: 'DEPOSIT_SUCCESS',
  DEPOSIT_ERROR: 'DEPOSIT_ERROR',
  BATCH_TX_SUBMITTED: 'BATCH_TX_SUBMITTED',
  FILL_SUCCESS: 'FILL_SUCCESS',
  FILL_ERROR: 'FILL_ERROR',
  SWAP_SUCCESS: 'SWAP_SUCCESS',

  // Routing events
  SWAP_ROUTE_SELECTED: 'SWAP_ROUTE_SELECTED',
  TOKEN_SELECTOR_CONTRACT_SEARCH: 'TOKEN_SELECTOR_CONTRACT_SEARCH',

  // Capacity/liquidity CTA events
  CTA_SET_MAX_CAPACITY_CLICKED: 'CTA_SET_MAX_CAPACITY_CLICKED',
  CTA_SWITCH_ROUTE_CLICKED: 'CTA_SWITCH_ROUTE_CLICKED',
  CTA_MAX_CAPACITY_PROMPTED: 'CTA_MAX_CAPACITY_PROMPTED',

  // Multi-wallet selector events
  WALLET_SELECTOR_SELECT: 'WALLET_SELECTOR_SELECT',
  WALLET_SELECTOR_OPEN: 'WALLET_SELECTOR_OPEN',
  WALLET_SELECTOR_CLOSE: 'WALLET_SELECTOR_CLOSE',

  // Amount events
  MAX_AMOUNT_CLICKED: 'MAX_AMOUNT_CLICKED',

  // Chain filter events
  CURRENCY_STEP_CHAIN_FILTER: 'CURRENCY_STEP_CHAIN_FILTER',

  // Token verification events
  UNVERIFIED_TOKEN_ACCEPTED: 'UNVERIFIED_TOKEN_ACCEPTED',

  // Gas top-up events
  GAS_TOP_UP_TOGGLE: 'GAS_TOP_UP_TOGGLE',

  // Starred chain events — includes { chainId, chainName } in data
  CHAIN_STARRED: 'CHAIN_STARRED',
  CHAIN_UNSTARRED: 'CHAIN_UNSTARRED',

  // Common/shared events
  USER_REJECTED_WALLET: 'USER_REJECTED_WALLET',
  CONNECT_WALLET_CLICKED: 'CONNECT_WALLET_CLICKED',
  TRANSACTION_VALIDATING: 'TRANSACTION_VALIDATING',
  ADDRESS_MODAL_OPEN: 'ADDRESS_MODAL_OPEN',
  ADDRESS_MODAL_CONFIRMED: 'ADDRESS_MODAL_CONFIRMED'
} as const

export type EventName = (typeof EventNames)[keyof typeof EventNames]
